PACKAGE_NAME="zettlab-d8-fans"
PACKAGE_VERSION="0.0.2"

BUILT_MODULE_NAME[0]="zettlab_d8_fans"
DEST_MODULE_LOCATION[0]="/kernel/drivers/hwmon"
AUTOINSTALL="yes"

MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make clean"
